
import { PrismaClient, Prisma } from '@prisma/client';

const prisma = new PrismaClient();

const settingsData = {
    key: "singleton",
    siteTitle: "বন্ধন'১৭",
    logoUrl: "https://res.cloudinary.com/dv5knrjpx/image/upload/v1755285088/bondhon17/q7bmkwkwkqcvikpekwmb.png",
    logoPublicId: "bondhon17/q7bmkwkwkqcvikpekwmb",
    minMonthlySavings: 1000,
    shareValue: 1000,
    policyContent: "✨ বন্ধন'১৭ (Bandhan17) নীতিমালা\r\n— সর্বশেষ হালনাগাদ ১২/০৮/২০২৫ ইং\r\n\r\n\r\n📖 ভূমিকা\r\n🌱 সুন্দর ভবিষ্যৎ গড়ার লক্ষ্যে সঞ্চয় হচ্ছে আয়ের একটি অংশ যা বর্তমানে ভোগ না করে ভবিষ্যতের জন্য জমা করে রাখা হয়।\r\n🤝 বন্ধন'১৭ একটি সঞ্চয়ভিত্তিক আর্থিক পরিকল্পনা, যা ২০১৭ সালের এসএসসি ব্যাচের বন্ধুদের ঐক্যবদ্ধ প্রচেষ্টায় গঠিত।\r\n🎯 আমাদের লক্ষ্য হচ্ছে ভবিষ্যতের জন্য একটি শক্ত ভিত্তি তৈরি করা, যাতে সবাই মিলিতভাবে বিভিন্ন উন্নয়নমূলক কর্মকাণ্ডে অংশ নিতে পারে।\r\n\r\n🎯 উদ্দেশ্য ও ভবিষ্যৎ পরিকল্পনা\r\n📅 মেয়াদ: আগস্ট ২০২৫ ➝ আগস্ট ২০৩৫ (১০ বছর)\r\n📌 আগস্ট ২০২৫ – আগস্ট ২০২৬ = ১ম অর্থবছর\r\n\r\n🔑 আমাদের টার্গেট:\r\n1️⃣ 🏞️ জমি কেনা\r\n2️⃣ 🏢 ফ্ল্যাট ও ভবন নির্মাণ\r\n3️⃣ 🏥 মিনি হাসপাতাল ও ডায়াগনস্টিক সেন্টার\r\n4️⃣ 🎓 প্রাইভেট স্কুল ও কলেজ\r\n5️⃣ 🛍️ ব্যবসা-বাণিজ্য (শপ, ফার্মেসি ইত্যাদি)\r\n6️⃣ 🚗 বিলাসদ্রব্য ক্রয়\r\n7️⃣ 💹 সুদবিহীন অর্থনৈতিক কার্যক্রমে বিনিয়োগ\r\n\r\n🏦 ব্যাংক অ্যাকাউন্ট\r\n💰 সকল সঞ্চয় থাকবে নির্ভরযোগ্য **সেভিংস একাউন্টে**।\r\n✍️ উত্তোলনের জন্য কমপক্ষে ৫ জন দায়িত্বপ্রাপ্ত সদস্যের স্বাক্ষর লাগবে।\r\n\r\n💵 মূলধন সংগ্রহ ও চাঁদা\r\n\r\n📌 ১। মাসিক চাঁদা\r\n- 🏷️ ১০০০ টাকা (প্রতি মাসে)\r\n- 📆 ৫ – ১৫ তারিখের মধ্যে জমা\r\n- 📲 ব্যাংক ট্রান্সফার রিসিট/স্ক্রিনশট WhatsApp গ্রুপে দিতে হবে\r\n\r\n📌 ২। ঈদ বোনাস\r\n🕌 ঈদ-উল-ফিতর ও ঈদ-উল-আযহা → (১০০০+১০০)= **২০০০ টাকা**\r\n\r\n📌 ৩। নিয়মাবলী\r\n- অসুস্থ হলে সর্বোচ্চ ৩ মাসের চাঁদা একসাথে দেওয়া যাবে।\r\n\r\n📌 ৪। অতিরিক্ত মূলধন\r\n📢 বড় প্রকল্পে প্রয়োজনে অতিরিক্ত মূলধন → সকলের সম্মতিতে\r\n\r\n📌 ৫। চাঁদা বৃদ্ধি\r\n📈 পরবর্তী বছর সম্মতিক্রমে বাড়ানো যাবে।\r\n\r\n📌 ৬। হিসাব রক্ষণ\r\n📊 ক্যাশিয়ার প্রতি মাসে রেজিস্টারে লিপিবদ্ধ ও এক্সেল শিট শেয়ার করবেন।\r\n\r\n📌 ৭। ক্যাশিয়ার পরিবর্তন\r\n👥 ১ জন প্রধান + ৪ জন সহকারী = মোট ৫ সদস্যের ক্যাশিয়ার কমিটি\r\n\r\n📌 ৮। মাসিক সভা\r\n📆 প্রতি মাসের ২য় শুক্রবার, বিকাল ৩টা, WhatsApp গ্রুপে\r\n\r\n📌 ৯। বোর্ড মিটিং\r\n🕌 প্রতি বছর রমজানে বার্ষিক মিটিং (সবার উপস্থিতি বাধ্যতামূলক)\r\n\r\n🛠️ কার্যক্রম ও বাস্তবায়ন\r\n- 🛍️ ডিপার্টমেন্টাল শপ, ফার্মেসি, ব্যবসা\r\n- 🏞️ জমি ক্রয় ও উন্নয়ন\r\n- 🏥 স্বাস্থ্যসেবা (হাসপাতাল/ডায়াগনস্টিক)\r\n- 🏢 আবাসিক/বাণিজ্যিক ভবন\r\n- 🎓 শিক্ষা প্রতিষ্ঠান\r\n\r\n📊 সম্পদ ও লাভ/ক্ষতি বন্টন\r\n\r\n১। সদস্য সংখ্যা অনুযায়ী বন্টন\r\n- 💰 লাভ-ক্ষতি সমানভাবে বন্টন\r\n- 🏠 জমি/ফ্ল্যাট/ভবনের মালিকানা সকলের সমান\r\n\r\n২। ঋণ প্রদান\r\n- 💸 সর্বোচ্চ সদস্যের মোট সঞ্চয়ের ১/৩ পর্যন্ত\r\n- 📆 সর্বোচ্চ ৬ মাসে পরিশোধ\r\n- 📝 লিখিত চুক্তি আবশ্যক\r\n\r\n৩। ঋণ গ্রহণ\r\n❌ সংগঠনের নাম ব্যবহার করে বাইরে ঋণ নেওয়া যাবে না\r\n\r\n👥 সদস্য সংক্রান্ত\r\n\r\n১। যোগ্যতা\r\n- 🎓 ২০১৭ ব্যাচ, ধানুয়া কামালপুর কো-অপারেটিভ হাই স্কুলের ছাত্র\r\n- 📝 ক্যাশিয়ার কমিটিতে কাজ করার মানসিকতা\r\n\r\n২। সদস্য পদ বাতিল\r\n- ❌ ৩ মাস ইচ্ছাকৃতভাবে চাঁদা না দিলে\r\n- ✅ মূল সঞ্চয় (লভ্যাংশ ছাড়া) ফেরত দেওয়া হবে\r\n- ⚰️ মৃত্যু হলে উত্তরাধিকারী টাকা পাবে\r\n\r\n৩। হস্তান্তর\r\n❌ অনুমতি ছাড়া বিক্রি/হস্তান্তর করা যাবে না\r\n\r\n৪। সীমা\r\n👤 একজন সর্বোচ্চ ৩টি সদস্যপদ নিতে পারবে\r\n\r\n❤️ বন্ধুত্ব ও মানবিক মূল্যবোধ\r\n- বন্ধন'১৭ শুধু অর্থনৈতিক নয়, বরং একতা ও ভালোবাসার প্রতীক 💞\r\n- বিপদে-আপদে পাশে থাকা 🤲\r\n- সুখ-দুঃখ ভাগাভাগি করা 🎉😢\r\n- পরস্পরের প্রতি শ্রদ্ধা ও সহমর্মিতা বজায় রাখা 🤝\r\n\r\n✅ নীতিমালার অনুমোদন\r\n🗳️ সকল সদস্যের সর্বসম্মতিক্রমে এই নীতিমালা অনুমোদিত হলো。\r\n",
    maxSharesPerMember: 3,
    loanToSavingsRatioNumerator: 1,
    loanToSavingsRatioDenominator: 3,
    loanSystemEnabled: false,
};

const paymentAccountData = [
    {
      id: "cmeelyxy5001exjpxt8ob1pko",
      accountName: "bKash",
      accountType: "MobileBanking",
      accountNumber: "01789540043",
      bankName: null,
      notice: "এই বিকাশ নম্বারে কেশ আউট চার্জ সহ পাঠিয়ে এবং এখানে খরচের টাকা সংযুক্ত না করে শুধু সেভিংস এমাউন্ট ইনপুট করে পেমেন্ট ভেরিফিকেশনের জন্য সাবমিট করুন।",
    },
    {
      id: "cmeem07r7001fxjpxbgy81564",
      accountName: "Nagad",
      accountType: "MobileBanking",
      accountNumber: "01789540043",
      bankName: null,
      notice: "এই নগদ নম্বারে কেশ আউট চার্জ সহ পাঠিয়ে এখানে খরচের টাকা সংযুক্ত না করে শুধু সেভিংস এমাউন্ট ইনপুট করে পেমেন্ট ভেরিফিকেশনের জন্য সাবমিট করুন।",
    },
    {
      id: "cmeem4yfx001gxjpxybjre79v",
      accountName: "ZIAUL HOQUE",
      accountType: "Bank",
      accountNumber": "1111187925308",
      bankName: "AB Bank",
      notice": "ব্রাঞ্চের নাম: BANANI BRANCH, রাউটিং নাম্বার: 020260433। উক্ত ব্যাংক একাউন্টে খরচ ছাড়া শুধু মাসিক চাদা পাঠিয়ে এখানে ভেরিফিকেশনের জন্য সাবমিট করুন।",
    },
    {
      id: "cmeemexp50004k095s7jit0qt",
      accountName: "Upai",
      accountType: "MobileBanking",
      accountNumber: "01789540043",
      bankName: null,
      notice: "এই উপাই নম্বারে কেশ আউট চার্জ সহ পাঠিয়ে এখানে খরচের টাকা সংযুক্ত না করে শুধু সেভিংস এমাউন্ট ইনপুট করে পেমেন্ট ভেরিফিকেশনের জন্য সাবমিট করুন।",
    },
    {
      id: "cmeemhuby001hxjpxmu9e74cj",
      accountName: "ZIAUL HOQUE",
      accountType: "Bank",
      accountNumber": "2394274200001",
      bankName: "The City Bank PLC ",
      notice": "Branch Name: GULSHAN BRANCH\r\nRouting Number:\t225261729\r\nউপরোক্ত ব্যাংকে খরচ ছাড়া মাসিক চাদা পাঠিয়ে এখানে ভেরিফিকেশনের জন্য সাবমিট করুন।\r\n",
    },
    {
      id: "cmeemjwp4001ixjpxi6bgnj4e",
      accountName: "Rocket",
      accountType: "MobileBanking",
      accountNumber": "017895400431",
      bankName": null,
      notice: "এটি একটি কর্পোরেট একাউন্ট,  এখানে কেশ আউট চার্জ সহ টাকা পাঠিয়ে, শুধু মাসিক চাদা দিয়ে ভেরিফিকেশনের জন্য সাবমিট করুন।",
    },
    {
      id: "cmer1k98t000066ebayr1x0h1",
      accountName: "Asfakul Hasibul Nur",
      accountType: "Bank",
      accountNumber": "404712100003590",
      bankName: "SJIBPLC",
      notice: "ব্যাংক: শাহজালাল ইসলামি ব্যাংক\r\nব্রাঞ্চ: জামালপুর\r\nরাউটিং নাম্বার: (এড করা হবে)\r\nবন্ধন ১৭ এর অফিসিয়াল ব্যাংক।",
    }
];

const memberData: Prisma.MemberCreateInput[] = [
  {
    "id": "68d97e5a38bcedba8a38af3a",
    "clerkId": "user_30qeWL3P1qXyUruasbSzDgm5oxw",
    "status": "Approved",
    "joiningType": "Old",
    "advanceBalance": 0,
    "fullNameBn": "বিল্লাল হোসেন",
    "fullNameEn": "Billal hossen",
    "fatherName": "হুমায়ুন কবীর",
    "motherName": "বেলেরানী",
    "nid": "2858559160",
    "dob": new Date("2000-10-09T00:00:00.000Z"),
    "bloodGroup": "AB+",
    "maritalStatus": "married",
    "religion": "Islam",
    "mobilePrimary": "01768226973",
    "mobileAlternate": "",
    "email": "mrbillu981820@gmail.com",
    "currentAddress": "kamalpur",
    "permanentAddress": "Kamalpur",
    "sscBatch": "2017",
    "otherEducation": "Hsc",
    "profession": "Paloder operator",
    "workplace": "Kamalpur lc station",
    "bankName": "",
    "branch": "",
    "accountNumber": "TEMP_ACC_1755368851615",
    "accountType": "savings",
    "bankingMethod": "",
    "nomineeName": "",
    "nomineeRelation": "",
    "nomineeMobile": "",
    "nomineeAddress": "",
    "photoUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759139440/bondhon17/op7mnwnlw0uunix5wi21.jpg",
    "nidCopyUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759139440/bondhon17/htutnlqpsn4kgb1dyqdh.jpg",
    "bankStatementUrl": null,
    "photoPublicId": "bondhon17/op7mnwnlw0uunix5wi21",
    "nidCopyPublicId": "bondhon17/htutnlqpsn4kgb1dyqdh",
    "bankStatementPublicId": null,
    "joiningDate": new Date("2025-08-17T00:00:00.000Z"),
  },
  {
    "id": "68d97e5a38bcedba8a38af3b",
    "clerkId": "user_30qaiJNC0wcs3n8Rz0ztwngFNlR",
    "status": "Approved",
    "joiningType": "Old",
    "advanceBalance": 0,
    "fullNameBn": "আব্দুর রহমান",
    "fullNameEn": "Abdur Rahman",
    "fatherName": "Abdur Rouf",
    "motherName": "Sufia Khatun",
    "nid": "6908670349",
    "dob": new Date("2000-11-10T00:00:00.000Z"),
    "bloodGroup": "B+",
    "maritalStatus": "married",
    "religion": "ইসলাম",
    "mobilePrimary": "01612282269",
    "mobileAlternate": "",
    "email": "suvonrahman121@gmail.com",
    "currentAddress": "ধানুয়া কামালপুর, বকশিগঞ্জ, জামালপুর",
    "permanentAddress": "ধানুয়া কামালপুর, বকশিগঞ্জ, জামালপুর",
    "sscBatch": "2017",
    "otherEducation": "আয়েপাশ",
    "profession": "শিক্ষক",
    "workplace": "ধানুয়া কামালপুর ইসলামিয়া দাখিল মাদরাসা",
    "bankName": "বিকাশ",
    "branch": "স্থানীয়",
    "accountNumber": "0162282269",
    "accountType": "savings",
    "bankingMethod": "মোবাইল",
    "nomineeName": "জুই",
    "nomineeRelation": "স্ত্রী",
    "nomineeMobile": "01799344866",
    "nomineeAddress": "ধানুয়া কামালপুর, বকশিগঞ্জ, জামালপুর",
    "photoUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759144005/bondhon17/v705wokv0lu7sz8rozrs.jpg",
    "nidCopyUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759144006/bondhon17/lxb1qodqylgwgbnirtmd.jpg",
    "bankStatementUrl": null,
    "photoPublicId": "bondhon17/v705wokv0lu7sz8rozrs",
    "nidCopyPublicId": "bondhon17/lxb1qodqylgwgbnirtmd",
    "bankStatementPublicId": null,
    "joiningDate": new Date("2025-08-17T00:00:00.000Z"),
  },
  {
    "id": "68d97e5a38bcedba8a38af3c",
    "clerkId": "user_30rFR6RytyQwA6ICQJMvfpERxae",
    "status": "Approved",
    "joiningType": "Old",
    "advanceBalance": 0,
    "fullNameBn": "রাকিব মিয়া",
    "fullNameEn": "Rakib Mia",
    "fatherName": "লুৎফর রহমান",
    "motherName": "আবেদা খাতুন",
    "nid": "৪৬৬০৭৩৮৪৬১",
    "dob": new Date("2001-05-10T00:00:00.000Z"),
    "bloodGroup": "A+",
    "maritalStatus": "married",
    "religion": "ইসলাম",
    "mobilePrimary": "TEMP_MOB_1755368907373",
    "mobileAlternate": "",
    "email": "rmia18638@gmail.com",
    "currentAddress": "মাস্টার বাড়ি",
    "permanentAddress": "মিরধাপাড়া,  বকশিগঞ্জ, জামালপুর",
    "sscBatch": "২০১৭",
    "otherEducation": "",
    "profession": "",
    "workplace": "",
    "bankName": "",
    "branch": "",
    "accountNumber": "TEMP_ACC_1755368907373",
    "accountType": "savings",
    "bankingMethod": "",
    "nomineeName": "",
    "nomineeRelation": "",
    "nomineeMobile": "",
    "nomineeAddress": "",
    "photoUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759144177/bondhon17/bxgx9gjsrf7gjnjuscot.png",
    "nidCopyUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759144177/bondhon17/laa8hz7rlsvgebckb7wc.jpg",
    "bankStatementUrl": null,
    "photoPublicId": "bondhon17/bxgx9gjsrf7gjnjuscot",
    "nidCopyPublicId": "bondhon17/laa8hz7rlsvgebckb7wc",
    "bankStatementPublicId": null,
    "joiningDate": new Date("2025-08-17T00:00:00.000Z"),
  },
  {
    "id": "68d97e5a38bcedba8a38af3d",
    "clerkId": "user_30rAVgBp20CrBshw2MqZspSW2Js",
    "status": "Approved",
    "joiningType": "Old",
    "advanceBalance": 0,
    "fullNameBn": "গোলাম রসুল",
    "fullNameEn": "Golam Rosul",
    "fatherName": "ইলিয়াস হোসেন",
    "motherName": "খোরশেদা বেগম",
    "nid": "6008548684",
    "dob": new Date("2000-11-01T00:00:00.000Z"),
    "bloodGroup": "A+",
    "maritalStatus": "married",
    "religion": "ইসলাম",
    "mobilePrimary": "01775262759",
    "mobileAlternate": "",
    "email": "grosul5709@gmail.com",
    "currentAddress": "Gazipur, mauna",
    "permanentAddress": "মাঝ গেদরা",
    "sscBatch": "2017",
    "otherEducation": "ডিগ্রি",
    "profession": "মার্চেন্ডাইজার",
    "workplace": "Denimach ltd",
    "bankName": "Dutch bangla Bank",
    "branch": "Bagher bajar",
    "accountNumber": "28010303877",
    "accountType": "current",
    "bankingMethod": "Online",
    "nomineeName": "ইলিয়াস হোসেন",
    "nomineeRelation": "বাবা",
    "nomineeMobile": "01756435431",
    "nomineeAddress": "মাঝ গেদরা",
    "photoUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759143549/bondhon17/i13rxc4gdhjjewgngei8.png",
    "nidCopyUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759143549/bondhon17/qeizf0p0ovzw7rpaa08i.jpg",
    "bankStatementUrl": null,
    "photoPublicId": "bondhon17/i13rxc4gdhjjewgngei8",
    "nidCopyPublicId": "bondhon17/qeizf0p0ovzw7rpaa08i",
    "bankStatementPublicId": null,
    "joiningDate": new Date("2025-08-17T00:00:00.000Z"),
  },
  {
    "id": "68d97e5a38bcedba8a38af3e",
    "clerkId": "user_30q7F53rFfGfvsrUOmEbnaOfIW7",
    "status": "Approved",
    "joiningType": "Old",
    "advanceBalance": 0,
    "fullNameBn": "আশফাকুল ইসলাম",
    "fullNameEn": "ASFAKUL ISLAM",
    "fatherName": "AMIRUL ISLAM",
    "motherName": "SELIMA BEGUM",
    "nid": "6458544977",
    "dob": new Date("2000-12-30T00:00:00.000Z"),
    "bloodGroup": "O+",
    "maritalStatus": "unmarried",
    "religion": "ইসলাম",
    "mobilePrimary": "01734737294",
    "mobileAlternate": "",
    "email": "asfakulislamsiam@gmail.com",
    "currentAddress": "বকশিগঞ্জ",
    "permanentAddress": "কামালপুর বাজার",
    "sscBatch": "২০১৭",
    "otherEducation": "Diploma in Engineering (CST)",
    "profession": "Job",
    "workplace": "Brand Promoter, Infinix",
    "bankName": "DBL",
    "branch": "Jamalpur",
    "accountNumber": "2067348739614",
    "accountType": "savings",
    "bankingMethod": "চেক বই",
    "nomineeName": "SELINA BEGUM",
    "nomineeRelation": "MOTHER",
    "nomineeMobile": "01312523391",
    "nomineeAddress": "কামালপুর বাজার",
    "photoUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759139060/bondhon17/ylz4kljarrcfyppgyddj.png",
    "nidCopyUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759139061/bondhon17/kvookarhdiew3hfx5tdy.png",
    "bankStatementUrl": null,
    "photoPublicId": "bondhon17/ylz4kljarrcfyppgyddj",
    "nidCopyPublicId": "bondhon17/kvookarhdiew3hfx5tdy",
    "bankStatementPublicId": null,
    "joiningDate": new Date("2025-08-17T00:00:00.000Z"),
  },
  {
    "id": "68d97e5a38bcedba8a38af3f",
    "clerkId": "user_30rPAk5KU9LRP9aO1H0tvnahxbw",
    "status": "Approved",
    "joiningType": "Old",
    "advanceBalance": 0,
    "fullNameBn": "মোঃ ইলিয়াস মিয়া",
    "fullNameEn": "Md Elias Mia",
    "fatherName": "মৃত ছাবু মিয়া",
    "motherName": "মোছাঃ সাজেদা বেগম",
    "nid": "4673403822",
    "dob": new Date("2001-03-30T00:00:00.000Z"),
    "bloodGroup": "B+",
    "maritalStatus": "married",
    "religion": "Islam",
    "mobilePrimary": "01935246460",
    "mobileAlternate": "",
    "email": "mdeliassunny01737459198@gmail.com",
    "currentAddress": "গাজীপুর",
    "permanentAddress": "ধানুয়া বাগান বাড়ি",
    "sscBatch": "2017",
    "otherEducation": "ডিগ্রী",
    "profession": "চাকরিজীবী",
    "workplace": "",
    "bankName": "Rocket",
    "branch": "",
    "accountNumber": "01935246460",
    "accountType": "current",
    "bankingMethod": "নিজস্ব",
    "nomineeName": "মোঃ তামজিদ ইসলাম নোমান",
    "nomineeRelation": "পিতা",
    "nomineeMobile": "01935246460",
    "nomineeAddress": "ধানুয়া বাগান বাড়ি",
    "photoUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759143459/bondhon17/cq0p05bixmhlckamh3cg.png",
    "nidCopyUrl": null,
    "bankStatementUrl": null,
    "photoPublicId": "bondhon17/cq0p05bixmhlckamh3cg",
    "nidCopyPublicId": null,
    "bankStatementPublicId": null,
    "joiningDate": new Date("2025-08-17T00:00:00.000Z"),
  },
  {
    "id": "68d97e5a38bcedba8a38af40",
    "clerkId": "user_30rtKP9Og5Vy2soIDxbfQNKKyJl",
    "status": "Approved",
    "joiningType": "Old",
    "advanceBalance": 0,
    "fullNameBn": "শাকিল আহম্মেদ",
    "fullNameEn": "Shakil Ahmed",
    "fatherName": "Abdul Awal",
    "motherName": "Shahida Begum",
    "nid": "6458682280",
    "dob": new Date("2001-12-24T00:00:00.000Z"),
    "bloodGroup": "O+",
    "maritalStatus": "unmarried",
    "religion": "Islam",
    "mobilePrimary": "01753-521549",
    "mobileAlternate": "",
    "email": "smshakilmahmud2001@gmail.com",
    "currentAddress": "সৌদি আরব",
    "permanentAddress": "ঘাসিরপাড়া (সরকার বাড়ি)",
    "sscBatch": "২০১৭",
    "otherEducation": "HSC",
    "profession": "Worker",
    "workplace": "Jeddah,Saudi Arabia",
    "bankName": "Islamic Bank Limited",
    "branch": "Bakshigang",
    "accountNumber": "20503310200970415",
    "accountType": "savings",
    "bankingMethod": "নিজস্ব",
    "nomineeName": "Shahida Begum",
    "nomineeRelation": "মাতা",
    "nomineeMobile": "01710422903",
    "nomineeAddress": "ঘাসিরপাড়া(সরকার বাড়ি)",
    "photoUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759143283/bondhon17/l9uycdo4cwsjdwnjtwea.jpg",
    "nidCopyUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759143284/bondhon17/ip0jyf6kvnqwouy9fc4g.jpg",
    "bankStatementUrl": null,
    "photoPublicId": "bondhon17/l9uycdo4cwsjdwnjtwea",
    "nidCopyPublicId": "bondhon17/ip0jyf6kvnqwouy9fc4g",
    "bankStatementPublicId": null,
    "joiningDate": new Date("2025-08-17T00:00:00.000Z"),
  },
  {
    "id": "68d97e5a38bcedba8a38af41",
    "clerkId": "user_30rfCPJjNZp0CxicpLkpeBoR5KR",
    "status": "Approved",
    "joiningType": "Old",
    "advanceBalance": 0,
    "fullNameBn": "ZIAUL HOQUE",
    "fullNameEn": "ZIAUL HOQUE",
    "fatherName": "DULA MIA",
    "motherName": "RABIA KHATUN",
    "nid": "1958676700",
    "dob": new Date("2001-01-11T00:00:00.000Z"),
    "bloodGroup": "A+",
    "maritalStatus": "married",
    "religion": "ISLAM",
    "mobilePrimary": "01789540043",
    "mobileAlternate": "",
    "email": "ziaulkobirpolash@gmail.com",
    "currentAddress": "HOUSE-03, ROAD- 13, BLOCK-C, BANASREE, RAMPURA, DHAKA- 1212",
    "permanentAddress": "SATANIPARA, DHANUA KAMALPUR, BAKSHIGANJ, JAMALPUR",
    "sscBatch": "2017",
    "otherEducation": "Bsc in CSE (Running)",
    "profession": "Visa processing Expert and Tour Operator",
    "workplace": "SAILOR TOURS AND TRAVELS LTD.",
    "bankName": "The City Bank PLC",
    "branch": "Gulshan Branch",
    "accountNumber": "2394274200001",
    "accountType": "savings",
    "bankingMethod": "Online",
    "nomineeName": "Ashrafun Nahar Omie",
    "nomineeRelation": "Spouse",
    "nomineeMobile": "01518905068",
    "nomineeAddress": "Same as me",
    "photoUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759143177/bondhon17/a1ot1zoo1061ustigvsp.jpg",
    "nidCopyUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759143177/bondhon17/jzfizip5lbdfhnldrnys.jpg",
    "bankStatementUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759143178/bondhon17/gno0fl52ru96pncz3k4s.jpg",
    "photoPublicId": "bondhon17/a1ot1zoo1061ustigvsp",
    "nidCopyPublicId": "bondhon17/jzfizip5lbdfhnldrnys",
    "bankStatementPublicId": "bondhon17/gno0fl52ru96pncz3k4s",
    "joiningDate": new Date("2025-08-17T00:00:00.000Z"),
  },
  {
    "id": "68d97e5a38bcedba8a38af42",
    "clerkId": "user_31SkHB7Jyrra2urBMw0Ccby86fP",
    "status": "Approved",
    "joiningType": "Old",
    "advanceBalance": 0,
    "fullNameBn": "মোঃ স্বাধীন",
    "fullNameEn": "Md Shadin",
    "fatherName": "মোঃ গুলাম আলি",
    "motherName": "মোছাঃ রহিতন",
    "nid": "৯১৫৮৫৩২৫৬৫",
    "dob": new Date("2000-11-12T00:00:00.000Z"),
    "bloodGroup": "O+",
    "maritalStatus": "unmarried",
    "religion": "ইসলাম",
    "mobilePrimary": "০১৭৫৩৪৫০৪৮০",
    "mobileAlternate": "",
    "email": "rejuan@gmail.com",
    "currentAddress": "বালুগাঁও, বকশিগঞ্জ,  জামালপুর",
    "permanentAddress": "ঐ",
    "sscBatch": "২০১৭",
    "otherEducation": "আলিম",
    "profession": "নাই",
    "workplace": "নাই",
    "bankName": "নাই",
    "branch": "নাই",
    "accountNumber": "নাই",
    "accountType": "current",
    "bankingMethod": "নাই",
    "nomineeName": "আব্দুর রহমান",
    "nomineeRelation": "ভাতিজা",
    "nomineeMobile": "০১৭৮৯৮৬২০২৭",
    "nomineeAddress": "বালুগাঁও, বকশিগঞ্জ, জামালপুর",
    "photoUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759143071/bondhon17/d9uwd4pg8gk7ldazlhpz.jpg",
    "nidCopyUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759143072/bondhon17/mhnqkqquzlqtf2i1pozl.jpg",
    "bankStatementUrl": null,
    "photoPublicId": "bondhon17/d9uwd4pg8gk7ldazlhpz",
    "nidCopyPublicId": "bondhon17/mhnqkqquzlqtf2i1pozl",
    "bankStatementPublicId": null,
    "joiningDate": new Date("2025-08-17T00:00:00.000Z"),
  },
  {
    "id": "68d97e5a38bcedba8a38af43",
    "clerkId": "user_30wxOQdUym54XdVozybfSbfbc02",
    "status": "Approved",
    "joiningType": "Old",
    "advanceBalance": 0,
    "fullNameBn": "মোবারক হোসেন",
    "fullNameEn": "Mubarak Hussen",
    "fatherName": "মনিরুল ইসলাম",
    "motherName": "জমিলা বেগম",
    "nid": "5102546669",
    "dob": new Date("1999-06-06T00:00:00.000Z"),
    "bloodGroup": "O+",
    "maritalStatus": "married",
    "religion": "Islam",
    "mobilePrimary": "01740509378",
    "mobileAlternate": "",
    "email": "mubarakhussen1956@gmail.com",
    "currentAddress": "কামাল পুর",
    "permanentAddress": "ধানুয়া কামাল পুর",
    "sscBatch": "2017",
    "otherEducation": "",
    "profession": "চাকরি",
    "workplace": "",
    "bankName": "",
    "branch": "",
    "accountNumber": "TEMP_ACC_1755369067741",
    "accountType": "savings",
    "bankingMethod": "",
    "nomineeName": "মনিরুল ইসলাম",
    "nomineeRelation": "বাবা",
    "nomineeMobile": "01759066044",
    "nomineeAddress": "কামাল পুর",
    "photoUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759142979/bondhon17/ksxb4qjpcy6qqnstdv0p.jpg",
    "nidCopyUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759142979/bondhon17/ktdoh43yxtjkn580tmcm.jpg",
    "bankStatementUrl": null,
    "photoPublicId": "bondhon17/ksxb4qjpcy6qqnstdv0p",
    "nidCopyPublicId": "bondhon17/ktdoh43yxtjkn580tmcm",
    "bankStatementPublicId": null,
    "joiningDate": new Date("2025-08-17T00:00:00.000Z"),
  },
  {
    "id": "68d97e5a38bcedba8a38af44",
    "clerkId": "user_30tisPAapfIKRVwLkTLi0i93HXy",
    "status": "Approved",
    "joiningType": "Old",
    "advanceBalance": 0,
    "fullNameBn": "আজিজুর রহমান",
    "fullNameEn": "Azizur Rahman",
    "fatherName": "Abu Taleb",
    "motherName": "Rongmala Begum",
    "nid": "5114951238",
    "dob": new Date("2001-03-20T00:00:00.000Z"),
    "bloodGroup": "O+",
    "maritalStatus": "unmarried",
    "religion": "Islam",
    "mobilePrimary": "01798442258",
    "mobileAlternate": "",
    "email": "aziz.mpicse@gmail.com",
    "currentAddress": "Sreepur, Ashulia, Dhaka",
    "permanentAddress": "Shatanipara",
    "sscBatch": "۲۰১৭",
    "otherEducation": "Diploma in CSE - MBPI, BSc in CSE - UU",
    "profession": "Job",
    "workplace": "Jr. Officer (Garments Industries)",
    "bankName": "IBBL",
    "branch": "Gazipur Sadar",
    "accountNumber": "20507776702108782",
    "accountType": "savings",
    "bankingMethod": "নিজস্ব",
    "nomineeName": "Md. Ranzu Mia",
    "nomineeRelation": "ভাই",
    "nomineeMobile": "01768419248",
    "nomineeAddress": "Kishorganj",
    "photoUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759142881/bondhon17/nifpbkf0aagm9zn5ubzx.jpg",
    "nidCopyUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759142881/bondhon17/a5bdz3qucztgkgollhbt.jpg",
    "bankStatementUrl": null,
    "photoPublicId": "bondhon17/nifpbkf0aagm9zn5ubzx",
    "nidCopyPublicId": "bondhon17/a5bdz3qucztgkgollhbt",
    "bankStatementPublicId": null,
    "joiningDate": new Date("2025-08-17T00:00:00.000Z"),
  },
  {
    "id": "68d97e5a38bcedba8a38af45",
    "clerkId": "user_30vIu57aEx7bPgjmtvxwFFkNmrV",
    "status": "Approved",
    "joiningType": "Old",
    "advanceBalance": 0,
    "fullNameBn": "রুমান আহমেদ",
    "fullNameEn": "Roman Ahmed",
    "fatherName": "Gulam Azom",
    "motherName": "Ruma begum",
    "nid": "7358577570",
    "dob": new Date("2000-01-02T00:00:00.000Z"),
    "bloodGroup": "B+",
    "maritalStatus": "unmarried",
    "religion": "Islam",
    "mobilePrimary": "01738827442",
    "mobileAlternate": "",
    "email": "rfruman2018@gmail.com",
    "currentAddress": "Dhaka, Uttara",
    "permanentAddress": "Kamalapur",
    "sscBatch": "2017",
    "otherEducation": "BA Honours",
    "profession": "Student",
    "workplace": "BA Honours, Dhaka, Uttara",
    "bankName": "",
    "branch": "",
    "accountNumber": "TEMP_ACC_1755369029525",
    "accountType": "savings",
    "bankingMethod": "",
    "nomineeName": "Golam Azom",
    "nomineeRelation": "বাবা",
    "nomineeMobile": "01748404918",
    "nomineeAddress": "Kamalpur, Dhanua Kamalpur",
    "photoUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759142646/bondhon17/uwfru2llp4zj7pl5nf5a.jpg",
    "nidCopyUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759142646/bondhon17/sras4zndnwvnmajq6j4p.png",
    "bankStatementUrl": null,
    "photoPublicId": "bondhon17/uwfru2llp4zj7pl5nf5a",
    "nidCopyPublicId": "bondhon17/sras4zndnwvnmajq6j4p",
    "bankStatementPublicId": null,
    "joiningDate": new Date("2025-08-17T00:00:00.000Z"),
  },
  {
    "id": "68d97e5a38bcedba8a38af46",
    "clerkId": "user_30v0fO6aeqhYqFHqwi2DqfLijmG",
    "status": "Approved",
    "joiningType": "Old",
    "advanceBalance": 0,
    "fullNameBn": "হাসিবুল হাসান",
    "fullNameEn": "Hasibul Hasan",
    "fatherName": "Abu Bakkar",
    "motherName": "Suria Begum",
    "nid": "6008570696",
    "dob": new Date("2002-03-02T00:00:00.000Z"),
    "bloodGroup": "A+",
    "maritalStatus": "unmarried",
    "religion": "Islam",
    "mobilePrimary": "01783564360",
    "mobileAlternate": "",
    "email": "shantobhaixyz@gmail.com",
    "currentAddress": "ধানুয়া কামালপুর ,বকশিগঞ্জ ,জামালপুর",
    "permanentAddress": "ধানুয়া কামালপুর ,বকশিগঞ্জ ,জামালপুর",
    "sscBatch": "২০১৭",
    "otherEducation": "HSC",
    "profession": "",
    "workplace": "",
    "bankName": "ইসলামী ব্যাংক",
    "branch": "বকশিগঞ্জ",
    "accountNumber": "20503310201293616",
    "accountType": "savings",
    "bankingMethod": "নিজস্ব",
    "nomineeName": "আবু বক্কর",
    "nomineeRelation": "বাবা",
    "nomineeMobile": "01734194799",
    "nomineeAddress": "ধানুয়া কামালপুর ,বকশিগঞ্জ ,জামালপুর",
    "photoUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759142544/bondhon17/cxlzodjcmdyebtgbk5y9.jpg",
    "nidCopyUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759142544/bondhon17/soobvxnlcfc1eav7jhdz.jpg",
    "bankStatementUrl": null,
    "photoPublicId": "bondhon17/cxlzodjcmdyebtgbk5y9",
    "nidCopyPublicId": "bondhon17/soobvxnlcfc1eav7jhdz",
    "bankStatementPublicId": null,
    "joiningDate": new Date("2025-08-17T00:00:00.000Z"),
  },
  {
    "id": "68d97e5a38bcedba8a38af47",
    "clerkId": "user_30uKtDtr0klleSOdUDyFVJ4mAiH",
    "status": "Approved",
    "joiningType": "Old",
    "advanceBalance": 0,
    "fullNameBn": "জাকিরুল",
    "fullNameEn": "Jakirul",
    "fatherName": "আবু সাইদ",
    "motherName": "রাবিয়া খাতুন",
    "nid": "8715550326",
    "dob": new Date("2000-01-03T00:00:00.000Z"),
    "bloodGroup": "B+",
    "maritalStatus": "married",
    "religion": "Islam",
    "mobilePrimary": "01984943815",
    "mobileAlternate": "",
    "email": "mdjakirulislam096@gmail.com",
    "currentAddress": "কালেখারবৈর,রাজনগর,রামপাল, বাগেরহাট",
    "permanentAddress": "সাতানীপাড়া",
    "sscBatch": "2017",
    "otherEducation": "",
    "profession": "চাকরি",
    "workplace": "বাংলাদেশ ইন্ডিয়া ফেন্ডসিপ পাওয়ার কমপানি লি. মি.",
    "bankName": "Dutch Bangla",
    "branch": "Rampal,Bagerhat",
    "accountNumber": "7017340811021",
    "accountType": "savings",
    "bankingMethod": "নিজস্ব",
    "nomineeName": "জোনাকি আক্তার",
    "nomineeRelation": "স্ত্রী",
    "nomineeMobile": "01735806968",
    "nomineeAddress": "সূর্যনগর",
    "photoUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759142444/bondhon17/lhxj6vvbycjsggs9zeyz.jpg",
    "nidCopyUrl": null,
    "bankStatementUrl": null,
    "photoPublicId": "bondhon17/lhxj6vvbycjsggs9zeyz",
    "nidCopyPublicId": null,
    "bankStatementPublicId": null,
    "joiningDate": new Date("2025-08-17T00:00:00.000Z"),
  },
  {
    "id": "68d97e5a38bcedba8a38af48",
    "clerkId": "user_30uGXqVnHBtxaCHlNHwj688dHHs",
    "status": "Approved",
    "joiningType": "Old",
    "advanceBalance": 0,
    "fullNameBn": "মোঃ কবিরুল ইসলাম",
    "fullNameEn": "Md. Kobirul Islam",
    "fatherName": "মোঃ সিরাজুল ইসলাম",
    "motherName": "মোছাঃ কুহুলা বেগম",
    "nid": "5110652830",
    "dob": new Date("2000-01-03T00:00:00.000Z"),
    "bloodGroup": "B+",
    "maritalStatus": "married",
    "religion": "ইসলাম",
    "mobilePrimary": "01701000902",
    "mobileAlternate": "",
    "email": "kabiruliskammd99@gamil.com",
    "currentAddress": "কোনাবাড়ি, নয়াপাড়া, কাশেমপুর",
    "permanentAddress": "কামালপুর, বকশিগঞ্জ",
    "sscBatch": "2017",
    "otherEducation": "",
    "profession": "চাকুরি",
    "workplace": "সহকারী সুপারভাইজার ( মনটেক্সস কমপ্লেক্স মন্ডলগ্রুপ )",
    "bankName": "রকেট",
    "branch": "",
    "accountNumber": "01701000902",
    "accountType": "savings",
    "bankingMethod": "নিজস্ব",
    "nomineeName": "মোছাঃ মিম আক্তার",
    "nomineeRelation": "স্ত্রী",
    "nomineeMobile": "",
    "nomineeAddress": "",
    "photoUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759142321/bondhon17/x6gvaqomanlhjsb5mbwo.png",
    "nidCopyUrl": null,
    "bankStatementUrl": null,
    "photoPublicId": "bondhon17/x6gvaqomanlhjsb5mbwo",
    "nidCopyPublicId": null,
    "bankStatementPublicId": null,
    "joiningDate": new Date("2025-08-17T00:00:00.000Z"),
  },
  {
    "id": "68d97e5a38bcedba8a38af49",
    "clerkId": "user_31UwDEYqsb1BA4cgurQ9vdlojiQ",
    "status": "Approved",
    "joiningType": "Old",
    "advanceBalance": 0,
    "fullNameBn": "লিখন মিয়া",
    "fullNameEn": "Likhon Mia",
    "fatherName": "ফুলু মিয়া",
    "motherName": "ময়না বেগম",
    "nid": "৩৩০৮৫১২০৫৬",
    "dob": new Date("2000-12-01T00:00:00.000Z"),
    "bloodGroup": "O+",
    "maritalStatus": "unmarried",
    "religion": "ইসলাম",
    "mobilePrimary": "",
    "mobileAlternate": "",
    "email": "mdlikhn138@gmail.com",
    "currentAddress": "কোনাবাড়ি",
    "permanentAddress": "ধানুয়া, বকশিগঞ্জ,  জামালপুর",
    "sscBatch": "২০১৭",
    "otherEducation": "",
    "profession": "ব্যবসা",
    "workplace": "কোনাবাড়ি",
    "bankName": "",
    "branch": "",
    "accountNumber": "",
    "accountType": "savings",
    "bankingMethod": "",
    "nomineeName": "ফুলু মিয়া",
    "nomineeRelation": "পিতা",
    "nomineeMobile": "",
    "nomineeAddress": "ধানুয়া",
    "photoUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759141623/bondhon17/yyhben2k7vzmnjuv44to.jpg",
    "nidCopyUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759141623/bondhon17/qp4g7mrndrkufptrxfnm.jpg",
    "bankStatementUrl": null,
    "photoPublicId": "bondhon17/yyhben2k7vzmnjuv44to",
    "nidCopyPublicId": "bondhon17/qp4g7mrndrkufptrxfnm",
    "bankStatementPublicId": null,
    "joiningDate": new Date("2025-08-17T00:00:00.000Z"),
  },
  {
    "id": "68d97e5a38bcedba8a38af4a",
    "clerkId": "user_30vYwjdgZQRrE4i7Tpw66FJbkTm",
    "status": "Approved",
    "joiningType": "Old",
    "advanceBalance": 0,
    "fullNameBn": "মো: আমির হোসেন",
    "fullNameEn": "MD. Amir Hosen",
    "fatherName": "মো: আবু সুফিয়ান",
    "motherName": "মোছা: ফরিদা বেগম",
    "nid": "6008552447",
    "dob": new Date("2000-10-11T00:00:00.000Z"),
    "bloodGroup": "O+",
    "maritalStatus": "married",
    "religion": "ইসলাম",
    "mobilePrimary": "01846334523",
    "mobileAlternate": "",
    "email": "myamir3345@gmail.com",
    "currentAddress": "ঢাকা",
    "permanentAddress": "ধানুয়া কামালপুর",
    "sscBatch": "2017",
    "otherEducation": "",
    "profession": "Driver",
    "workplace": "গাজী গ্রুপ",
    "bankName": "",
    "branch": "",
    "accountNumber": "TEMP_ACC_1755369056814",
    "accountType": "savings",
    "bankingMethod": "",
    "nomineeName": "ইসরাত জাহান",
    "nomineeRelation": "স্ত্রী",
    "nomineeMobile": "01768451422",
    "nomineeAddress": "ধানুয়া কামালপুর",
    "photoUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759141501/bondhon17/aklc1psaq8xxos8ghtwq.jpg",
    "nidCopyUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759141501/bondhon17/jhl0cm2vb8jvumdpaorx.jpg",
    "bankStatementUrl": null,
    "photoPublicId": "bondhon17/aklc1psaq8xxos8ghtwq",
    "nidCopyPublicId": "bondhon17/jhl0cm2vb8jvumdpaorx",
    "bankStatementPublicId": null,
    "joiningDate": new Date("2025-08-17T00:00:00.000Z"),
  },
  {
    "id": "68d97e5a38bcedba8a38af4b",
    "clerkId": "user_30xqnhXKTrOf7Lh2cphS2nMds5n",
    "status": "Approved",
    "joiningType": "Old",
    "advanceBalance": 0,
    "fullNameBn": "জিবু মিয়া",
    "fullNameEn": "Zibu Mia",
    "fatherName": "রুহুল আমিন",
    "motherName": "জুলেখা বেগম",
    "nid": "6008553163",
    "dob": new Date("2001-07-15T00:00:00.000Z"),
    "bloodGroup": "B+",
    "maritalStatus": "unmarried",
    "religion": "Islam",
    "mobilePrimary": "01763581606",
    "mobileAlternate": "",
    "email": "mdziburahman2@gmail.com",
    "currentAddress": "ধানুয়া",
    "permanentAddress": "ধানুয়া কামালপুর",
    "sscBatch": "2017",
    "otherEducation": "এইচএসসি",
    "profession": "ব্যবসা",
    "workplace": "গাড়ির ব্যবসা",
    "bankName": "",
    "branch": "",
    "accountNumber": "TEMP_ACC_1755369081008",
    "accountType": "savings",
    "bankingMethod": "",
    "nomineeName": "জুলেখা বেগম",
    "nomineeRelation": "মাতা",
    "nomineeMobile": "",
    "nomineeAddress": "ধানুয়া",
    "photoUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759141411/bondhon17/gcikh0jwmxpjsmy3uesz.png",
    "nidCopyUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759141412/bondhon17/fionljpppkmfoatdghb8.jpg",
    "bankStatementUrl": null,
    "photoPublicId": "bondhon17/gcikh0jwmxpjsmy3uesz",
    "nidCopyPublicId": "bondhon17/fionljpppkmfoatdghb8",
    "bankStatementPublicId": null,
    "joiningDate": new Date("2025-08-17T00:00:00.000Z"),
  },
  {
    "id": "68d97e5a38bcedba8a38af4c",
    "clerkId": "user_30uouxerRQAvOZLGIfJ5nBKNWIs",
    "status": "Approved",
    "joiningType": "Old",
    "advanceBalance": 0,
    "fullNameBn": "আবু হানিফ",
    "fullNameEn": "Abu Hanif",
    "fatherName": "ইসমাইল হোসেন",
    "motherName": "বুলবুলি বেগম",
    "nid": "3308544166",
    "dob": new Date("2001-05-01T00:00:00.000Z"),
    "bloodGroup": "O+",
    "maritalStatus": "married",
    "religion": "ইসলাম",
    "mobilePrimary": "01793409415",
    "mobileAlternate": "",
    "email": "abuhanifmondol129@gmail.com",
    "currentAddress": "হাজিপুর,জিনারী,হোসেনপুর,কিশোরগঞ্জ",
    "permanentAddress": "ধানুয়া কামালপুর",
    "sscBatch": "২০১৭",
    "otherEducation": "HSC",
    "profession": "চাকুরি",
    "workplace": "তারাপাশা অভিযোগ কেন্দ্র, হোসেনপুর জোনাল অফিস,কিশোরগঞ্জ পল্লী বিদ্যুৎ সমিতি",
    "bankName": "ডাচ্ বাংলা",
    "branch": "হোসেনপুর শাখা",
    "accountNumber": "2311030237572",
    "accountType": "savings",
    "bankingMethod": "নিজস্ব",
    "nomineeName": "শাকিলা আক্তার",
    "nomineeRelation": "স্ত্রী",
    "nomineeMobile": "01677344508",
    "nomineeAddress": "ধানুয়া,ধানুয়া কামালপুর, বকশিগঞ্জ, জামালপুর",
    "photoUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759141255/bondhon17/geon2qszcpy8xpriszyj.jpg",
    "nidCopyUrl": null,
    "bankStatementUrl": null,
    "photoPublicId": "bondhon17/geon2qszcpy8xpriszyj",
    "nidCopyPublicId": null,
    "bankStatementPublicId": null,
    "joiningDate": new Date("2025-08-17T00:00:00.000Z"),
  },
  {
    "id": "68d97e5a38bcedba8a38af4d",
    "clerkId": "user_30rKZuc63HL2OpiYDlpiS53lhk5",
    "status": "Approved",
    "joiningType": "Old",
    "advanceBalance": 0,
    "fullNameBn": "SYED ROFIKUNNOBI",
    "fullNameEn": "SYED ROFIKUNNOBI",
    "fatherName": "এস এম রাশেদুন্নবী",
    "motherName": "জান্নাতুল ফেরদৌসী",
    "nid": "৪২০৯৭১১২৫০",
    "dob": new Date("2000-12-20T00:00:00.000Z"),
    "bloodGroup": "B+",
    "maritalStatus": "married",
    "religion": "ইসলাম",
    "mobilePrimary": "০১৭১৬-৯০৭৫৯২",
    "mobileAlternate": "",
    "email": "rnabihm@gmail.com",
    "currentAddress": "নেভাল বার্থ,  নিউমুরিং, চট্টগ্রাম",
    "permanentAddress": "মিরধাপাড়া, বকশিগঞ্জ, জামালপুর",
    "sscBatch": "২০১৭",
    "otherEducation": "এইচএসসি,  ডিপ্লোমা ইন নেভাল মেরিন ইলেক্ট্রিক্যাল",
    "profession": "সামরিক চাকরিজীবি",
    "workplace": "বাংলাদেশ নৌবাহিনী",
    "bankName": "ট্রাস্ট ব্যাংক পিএলসি",
    "branch": "খুলনা",
    "accountNumber": "০১০৩-০২১৪০১৫৫৩৩",
    "accountType": "current",
    "bankingMethod": "অনলাইন",
    "nomineeName": "মনিরা আক্তার",
    "nomineeRelation": "স্ত্রী",
    "nomineeMobile": "০১৩১১-২৮৫০০৩",
    "nomineeAddress": "নয়াপাড়া, কলাবাগান, পাঁচ রাস্তা,  জামালপুর সদর, জামালপুর",
    "photoUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759140942/bondhon17/mdn1oryfpjvpc3edbzse.png",
    "nidCopyUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759140942/bondhon17/vw3k9gkqlogrduokding.jpg",
    "bankStatementUrl": null,
    "photoPublicId": "bondhon17/mdn1oryfpjvpc3edbzse",
    "nidCopyPublicId": "bondhon17/vw3k9gkqlogrduokding",
    "bankStatementPublicId": null,
    "joiningDate": new Date("2025-08-17T00:00:00.000Z"),
  },
  {
    "id": "68d97e5a38bcedba8a38af4e",
    "clerkId": "user_31EVHyHPyShHBxnl6blYQCyadoJ",
    "status": "Approved",
    "joiningType": "Old",
    "advanceBalance": 0,
    "fullNameBn": "আব্দুন নূর",
    "fullNameEn": "ABDUN NUR",
    "fatherName": "MOKTAR UDDIN",
    "motherName": "NURONNAHAR PARVIN",
    "nid": "8708636397",
    "dob": new Date("2003-05-05T00:00:00.000Z"),
    "bloodGroup": "B+",
    "maritalStatus": "unmarried",
    "religion": "ইসলাম",
    "mobilePrimary": "01789519756",
    "mobileAlternate": "",
    "email": "mdabdunnur54@gmail.com",
    "currentAddress": "বালুগাঁও",
    "permanentAddress": "বালুগাঁও,ধানুয়া কামালপুর",
    "sscBatch": "2017",
    "otherEducation": "অনার্স ৩য় বর্ষ",
    "profession": "ব্যবসা",
    "workplace": "NUR FASHION AND SPORTS",
    "bankName": "Islami Bank",
    "branch": "Agent banking",
    "accountNumber": "20507770222469379",
    "accountType": "savings",
    "bankingMethod": "নিজস্ব",
    "nomineeName": "মোক্তার উদ্দিন",
    "nomineeRelation": "বাবা",
    "nomineeMobile": "01789519756",
    "nomineeAddress": "বালুগাঁও, ধানুয়া কামালপুর, বকশিগঞ্জ, জামালপুর",
    "photoUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759140808/bondhon17/bcfvsas8bhdrb4rdas51.png",
    "nidCopyUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759140809/bondhon17/nwvbjm3vnzkvjbrmtznk.png",
    "bankStatementUrl": null,
    "photoPublicId": "bondhon17/bcfvsas8bhdrb4rdas51",
    "nidCopyPublicId": "bondhon17/nwvbjm3vnzkvjbrmtznk",
    "bankStatementPublicId": null,
    "joiningDate": new Date("2025-08-17T00:00:00.000Z"),
  },
  {
    "id": "68d97e5a38bcedba8a38af4f",
    "clerkId": "user_3132lM2li1NYU43uPxQWvgiHTrt",
    "status": "Approved",
    "joiningType": "Old",
    "advanceBalance": 0,
    "fullNameBn": "রাশিদ শাহরিয়ার",
    "fullNameEn": "Rashid Shahariar",
    "fatherName": "মাহফুজ রহমান",
    "motherName": "রাবেয়া সুলতানা",
    "nid": "5125439397",
    "dob": new Date("2000-12-30T00:00:00.000Z"),
    "bloodGroup": "O+",
    "maritalStatus": "married",
    "religion": "ইসলাম",
    "mobilePrimary": "01792416950",
    "mobileAlternate": "",
    "email": "rashidshahariarhridoy@gmail.com",
    "currentAddress": "ধানুয়া",
    "permanentAddress": "ধানুয়া",
    "sscBatch": "2017",
    "otherEducation": "HSC",
    "profession": "Job",
    "workplace": "বাংলাদেশ সেনাবাহিনী  রংপুর সেনানিবাস",
    "bankName": "ট্রাস্ট্ ব্যাংক",
    "branch": "রংপুর",
    "accountNumber": "TEMP_ACC_17553_NEED_TO_CHANGE",
    "accountType": "savings",
    "bankingMethod": "নিজস্ব",
    "nomineeName": "ছামিয়া জান্নাত মিমি",
    "nomineeRelation": "স্ত্রী",
    "nomineeMobile": "01792416950",
    "nomineeAddress": "ঘাসির পারা",
    "photoUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759140610/bondhon17/iofrjiatjhphkqxoajib.png",
    "nidCopyUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759140611/bondhon17/ivn22pc7n5u8ckb1oyig.jpg",
    "bankStatementUrl": null,
    "photoPublicId": "bondhon17/iofrjiatjhphkqxoajib",
    "nidCopyPublicId": "bondhon17/ivn22pc7n5u8ckb1oyig",
    "bankStatementPublicId": null,
    "joiningDate": new Date("2025-08-17T00:00:00.000Z"),
  },
  {
    "id": "68d97e5a38bcedba8a38af50",
    "clerkId": "user_30vRbImvEEKmUMaB46UxPFjSj7C",
    "status": "Approved",
    "joiningType": "Old",
    "advanceBalance": 0,
    "fullNameBn": "আল ইবনে জাকির",
    "fullNameEn": "Al Ibne Jakir",
    "fatherName": "কামরুজ্জামান",
    "motherName": "পারভিন আক্তার",
    "nid": "6008570837",
    "dob": new Date("2000-01-11T00:00:00.000Z"),
    "bloodGroup": "O+",
    "maritalStatus": "married",
    "religion": "Islam",
    "mobilePrimary": "01910917790",
    "mobileAlternate": "",
    "email": "prantos250@gmail.com",
    "currentAddress": "আড়াই হাজার নারায়ণগঞ্জ",
    "permanentAddress": "ঘাসিরপাড়া সরকার বাড়ি",
    "sscBatch": "2017",
    "otherEducation": "অনার্স",
    "profession": "মার্কেটিং",
    "workplace": "ইউনিভার্সাল কনজুমার ফুড প্রোডাক্টস লিমিটেড",
    "bankName": "ইসলামي ব্যাংক",
    "branch": "বকশিগঞ্জ",
    "accountNumber": "8433",
    "accountType": "savings",
    "bankingMethod": "নিজস্ব",
    "nomineeName": "তামান্না",
    "nomineeRelation": "স্ত্রী",
    "nomineeMobile": "01872453354",
    "nomineeAddress": "ঘাসিরপাড়া সরকার বাড়ি",
    "photoUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759140360/bondhon17/mta2lwj50q166our4ye9.jpg",
    "nidCopyUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759140361/bondhon17/rngb1hzfzi2jxicnzfvb.jpg",
    "bankStatementUrl": null,
    "photoPublicId": "bondhon17/mta2lwj50q166our4ye9",
    "nidCopyPublicId": "bondhon17/rngb1hzfzi2jxicnzfvb",
    "bankStatementPublicId": null,
    "joiningDate": new Date("2025-08-17T00:00:00.000Z"),
  },
  {
    "id": "68d97e5a38bcedba8a38af51",
    "clerkId": "user_30r9mTTnSMqCLhQ2AV0Q1SftIhg",
    "status": "Approved",
    "joiningType": "Old",
    "advanceBalance": 0,
    "fullNameBn": "মামুন মিয়া",
    "fullNameEn": "Mamun Mia",
    "fatherName": "তোজাম্মেল হক বকুল",
    "motherName": "মোর্শেদা বেগম",
    "nid": "২৮৫৮৪৯৬৩৬৩",
    "dob": new Date("2000-12-30T00:00:00.000Z"),
    "bloodGroup": "A+",
    "maritalStatus": "unmarried",
    "religion": "ইসলাম",
    "mobilePrimary": "০১৭৮৩-৭২২১৪৮",
    "mobileAlternate": "",
    "email": "mahmudulhasanmamun50@gmail.com",
    "currentAddress": "কোনাবাড়ি, কাশিমপুর, গাজীপুর",
    "permanentAddress": "উত্তর কামালপুর, বকশীগঞ্জ, জামালপুর",
    "sscBatch": "২০১৭",
    "otherEducation": "বি.এস.সি ইন টেক্সটাইল",
    "profession": "চাকুরী",
    "workplace": "মাইমুন কমপ্লেক্স,ডিবিএল গ্রুপ, কাশিমপুর, জিতার মোড়",
    "bankName": "ডাচ বাংলা ব্যাংক",
    "branch": "কাশিমপুর",
    "accountNumber": "০১৭৮৩-৭২২১৪৮৯",
    "accountType": "current",
    "bankingMethod": "মোবাইল ব্যাংকিং / রকেট",
    "nomineeName": "তোজাম্মেল হক বকুল",
    "nomineeRelation": "বাবা",
    "nomineeMobile": "০১৬১৩-৬৮০৪৩৯",
    "nomineeAddress": "উত্তর কামালপুর, বকশীগঞ্জ, জামালপুর",
    "photoUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759140115/bondhon17/ol7qsl7umtvbkd88hpku.jpg",
    "nidCopyUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759140116/bondhon17/gxjl6tz0tuoyhqygoh2i.jpg",
    "bankStatementUrl": null,
    "photoPublicId": "bondhon17/ol7qsl7umtvbkd88hpku",
    "nidCopyPublicId": "bondhon17/gxjl6tz0tuoyhqygoh2i",
    "bankStatementPublicId": null,
    "joiningDate": new Date("2025-08-17T00:00:00.000Z"),
  },
  {
    "id": "68d97e5a38bcedba8a38af52",
    "clerkId": "user_30rDm6EJRRmeunZsMaYx2FM4fYl",
    "status": "Approved",
    "joiningType": "Old",
    "advanceBalance": 0,
    "fullNameBn": "আতিকুর রহমান",
    "fullNameEn": "ATIKUR RAHMAN",
    "fatherName": "ফরজ আলী",
    "motherName": "মনোয়ারা বেগম",
    "nid": "6458545008",
    "dob": new Date("2000-11-21T00:00:00.000Z"),
    "bloodGroup": "O+",
    "maritalStatus": "unmarried",
    "religion": "ইসলাম",
    "mobilePrimary": "01911442279",
    "mobileAlternate": "",
    "email": "atikurrahmanamc1059@gmail.com",
    "currentAddress": "গ্রামঃ কামালপুর, ডাকঘরঃ ধানুয়া কামালপুর - ২১৪০, বকশীগঞ্জ, জামালপুর।",
    "permanentAddress": "গ্রামঃ কামালপুর, ডাকঘরঃ ধানুয়া কামালপুর - ২১৪০, বকশীগঞ্জ, জামালপুর।",
    "sscBatch": "2017",
    "otherEducation": "BSs Honours in Political Science.",
    "profession": "Student",
    "workplace": "Govt. Ashek Mahmud College, Jamalpur.",
    "bankName": "Bank Asia Ltd.",
    "branch": "Dhanua Kamalpur",
    "accountNumber": "1083439056361",
    "accountType": "savings",
    "bankingMethod": "অনলাইন ব্যাংকিং",
    "nomineeName": "ফরজ আলী",
    "nomineeRelation": "বাবা",
    "nomineeMobile": "01751636150",
    "nomineeAddress": "গ্রামঃ কামালপুর, ডাকঘরঃ ধানুয়া কামালপুর - ২১৪০, বকশীগঞ্জ, জামালপুর।",
    "photoUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759139848/bondhon17/goulbvrp5dps2tl3wjlg.jpg",
    "nidCopyUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759139849/bondhon17/ugkpfhbty0gce7qyewmv.jpg",
    "bankStatementUrl": null,
    "photoPublicId": "bondhon17/goulbvrp5dps2tl3wjlg",
    "nidCopyPublicId": "bondhon17/ugkpfhbty0gce7qyewmv",
    "bankStatementPublicId": null,
    "joiningDate": new Date("2025-08-17T00:00:00.000Z"),
  },
  {
    "id": "68d97e5a38bcedba8a38af53",
    "clerkId": "user_30qxjSAYIrSFr3e698NqH9YG9cu",
    "status": "Approved",
    "joiningType": "Old",
    "advanceBalance": 0,
    "fullNameBn": "শাহরিয়ার আহমেদ",
    "fullNameEn": "Shahriyar Ahmed",
    "fatherName": "খাইরুল ইসলাম",
    "motherName": "সুফিয়া বেগম",
    "nid": "2865255307",
    "dob": new Date("2000-11-30T00:00:00.000Z"),
    "bloodGroup": "B+",
    "maritalStatus": "married",
    "religion": "ইসলাম",
    "mobilePrimary": "01790559760",
    "mobileAlternate": "",
    "email": "shahriyar431585@gmail.com",
    "currentAddress": "ধানুয়া কামালপুর বকশিগঞ্জ জামালপুর",
    "permanentAddress": "ধানুয়া কামালপুর বকশিগঞ্জ জামালpur",
    "sscBatch": "2017",
    "otherEducation": "HSC",
    "profession": "",
    "workplace": "",
    "bankName": "",
    "branch": "",
    "accountNumber": "0000",
    "accountType": "savings",
    "bankingMethod": "",
    "nomineeName": "তামান্না আক্তার মিলি",
    "nomineeRelation": "স্ত্রী",
    "nomineeMobile": "01790559760",
    "nomineeAddress": "ধানুয়া কামালপুর বকশিগঞ্জ জামালপুর",
    "photoUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759139711/bondhon17/mudfygo3xqqkiuz2chdm.png",
    "nidCopyUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759139712/bondhon17/zi9farnlknt8h1ey2hzs.jpg",
    "bankStatementUrl": null,
    "photoPublicId": "bondhon17/mudfygo3xqqkiuz2chdm",
    "nidCopyPublicId": "bondhon17/zi9farnlknt8h1ey2hzs",
    "bankStatementPublicId": null,
    "joiningDate": new Date("2025-08-17T00:00:00.000Z"),
  },
  {
    "id": "68d97e5a38bcedba8a38af54",
    "clerkId": "user_31hEWBBR7r84TAYAskKnLDmc7jZ",
    "status": "Approved",
    "joiningType": "Old",
    "advanceBalance": 0,
    "fullNameBn": "Minhajul Islam",
    "fullNameEn": "Minhajul Islam",
    "fatherName": "",
    "motherName": "",
    "nid": "TEMP_NID_1755969505365",
    "dob": new Date("2001-12-11T00:00:00.000Z"),
    "bloodGroup": "A+",
    "maritalStatus": "unmarried",
    "religion": "",
    "mobilePrimary": "TEMP_MOB_1755969505365",
    "mobileAlternate": "",
    "email": "minhajulislam845250@gmail.com",
    "currentAddress": "",
    "permanentAddress": "",
    "sscBatch": "",
    "otherEducation": "",
    "profession": "",
    "workplace": "",
    "bankName": "",
    "branch": "",
    "accountNumber": "TEMP_ACC_1755969505365",
    "accountType": "savings",
    "bankingMethod": "",
    "nomineeName": "",
    "nomineeRelation": "",
    "nomineeMobile": "",
    "nomineeAddress": "",
    "photoUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759139437/bondhon17/vzs9qyqpxvojrguyawd0.jpg",
    "nidCopyUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759139438/bondhon17/fysjkz2dvxkb3szbp53k.jpg",
    "bankStatementUrl": null,
    "photoPublicId": "bondhon17/vzs9qyqpxvojrguyawd0",
    "nidCopyPublicId": "bondhon17/fysjkz2dvxkb3szbp53k",
    "bankStatementPublicId": null,
    "joiningDate": new Date("2025-08-17T00:00:00.000Z"),
  },
  {
    "id": "68d97e5a38bcedba8a38af55",
    "clerkId": "user_30s2EF4MZ6rE20vZKcu7ZIENSzI",
    "status": "Approved",
    "joiningType": "Old",
    "advanceBalance": 0,
    "fullNameBn": "মোঃ আতিকুর রহমান",
    "fullNameEn": "Md. Atikur Rahman",
    "fatherName": "গোলাম মোস্তফা",
    "motherName": "আছিয়া বেগম",
    "nid": "8708570570",
    "dob": new Date("2000-12-12T00:00:00.000Z"),
    "bloodGroup": "O+",
    "maritalStatus": "unmarried",
    "religion": "Islam",
    "mobilePrimary": "01816374753",
    "mobileAlternate": "",
    "email": "mdatikuraz37@gmail.com",
    "currentAddress": "কামালপুর",
    "permanentAddress": "ধানুয়া কামালপুর",
    "sscBatch": "2017",
    "otherEducation": "",
    "profession": "ব্যাবসা",
    "workplace": "কামালপুর বাজার",
    "bankName": "",
    "branch": "",
    "accountNumber": "TEMP_ACC_1755368971260",
    "accountType": "savings",
    "bankingMethod": "",
    "nomineeName": "আছিয়া বেগম",
    "nomineeRelation": "মাতা",
    "nomineeMobile": "01765637489",
    "nomineeAddress": "কামালপুর",
    "photoUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759139334/bondhon17/yj6flgzdbu0hosivmifa.jpg",
    "nidCopyUrl": "https://res.cloudinary.com/dzj1tkpks/image/upload/v1759139334/bondhon17/egjwjjttfhviymlpnbg2.jpg",
    "bankStatementUrl": null,
    "photoPublicId": "bondhon17/yj6flgzdbu0hosivmifa",
    "nidCopyPublicId": "bondhon17/egjwjjttfhviymlpnbg2",
    "bankStatementPublicId": null,
    "joiningDate": new Date("2025-08-17T00:00:00.000Z"),
  }
]
